const enrichText = (input, style) =>
  `Mode: ${style}\n\n${input
    .split(" ")
    .map((word, index) => (index % 7 === 0 ? word.toUpperCase() : word))
    .join(" ")}\n\nRefined by WriteEase AI mock engine for a cleaner, more natural result.`;

export const aiService = {
  humanize: async ({ text, mode }) => ({
    output: enrichText(text, mode),
    insights: [
      "Improved sentence flow",
      "Reduced repetitive phrasing",
      "Balanced tone for human readability"
    ]
  }),
  paraphrase: async ({ text, mode }) => ({
    output: enrichText(text, mode),
    insights: [
      "Reframed original wording",
      "Preserved core meaning",
      "Adjusted complexity to selected mode"
    ]
  }),
  grammarCheck: async ({ text }) => ({
    output: text.replace(/\bi\b/g, "I"),
    stats: {
      errorsFound: 4,
      correctionsApplied: 3
    },
    suggestions: [
      {
        type: "Capitalization",
        original: "i",
        suggested: "I",
        reason: "Pronoun should be capitalized"
      },
      {
        type: "Clarity",
        original: "very very important",
        suggested: "essential",
        reason: "Improves readability"
      }
    ]
  }),
  plagiarismScan: async ({ text }) => ({
    summary: {
      similarity: Math.min(38, Math.max(8, Math.floor(text.length / 25))),
      originality: 100 - Math.min(38, Math.max(8, Math.floor(text.length / 25)))
    },
    sources: [
      {
        title: "Research Writing Best Practices",
        url: "https://example.com/research-writing",
        match: "12%"
      },
      {
        title: "Academic Style Guide",
        url: "https://example.com/academic-style",
        match: "7%"
      }
    ]
  }),
  enhanceResume: async ({ personalInfo, skills = [] }) => ({
    headline: `${personalInfo?.role || "Professional"} with a strong foundation in ${skills
      .slice(0, 3)
      .join(", ")}`,
    summary:
      "Results-driven profile generated by the WriteEase AI mock service. Ready for further tailoring to a job description."
  })
};

